name: Python Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar el script
        run: python revision.py
