name: API Private Test

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar requests
        run: pip install requests
      
      - name: Instalar dotenv
        run: pip install dotenv
      

      - name: Ejecutar el script con API privada
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
        run: python script.py

          
      - name: crear txt
        uses: actions/upload-artifact@v4
        with:
          name: balance.txt
          path: balance.txt

